% Lamination 
function [toolMn, compLam, coilName] = ConstructLaminationExample(n)

MES_AirBox = 2; %Maximum Element Size in air (mm)
MES_Conductors = 2; %Maximum Element Size in conductors (mm)
MES_Laminations = 0.15; %Maximum Element Size in the laminations (mm)

CoilTurns = 1000; %Number of turns on the coil
lamT = 10/n; %lamination thickness

%% set up MagNet

toolMn = MagNet();
toolMn.open(0,0,true);
toolMn.setDefaultLengthUnit('millimeters', false);

%% MagNet Airbox
CsAir = CrossSectSolidRect( ...
        'name', 'Cond1', ...
        'dim_w',DimMillimeter(78),....
        'dim_h',DimMillimeter(90),...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([-30,-30]), ...
            'theta', DimDegree([0]).toRadians() ...
        ) ...
        );
compAir = Component( ...
        'name', 'Airbox', ...
        'crossSections', CsAir, ...
        'material', MaterialGeneric('name', 'AIR'), ...
        'makeSolid', MakeExtrude( ...
            'location', Location3D( ...
                'anchor_xyz', DimMillimeter([0,0,0]), ...
                'rotate_xyz', DimDegree([0,0,0]).toRadians() ...
                ), ...
            'dim_depth', DimMillimeter(10)) ...
        );
compAir.make(toolMn,toolMn);
toolMn.viewAll();

%% Conductors

CsCleft = CrossSectSolidRect( ...
        'name', 'Cond1', ...
        'dim_w',DimMillimeter(2),....
        'dim_h',DimMillimeter(25),...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([0,2.5]), ...
            'theta', DimDegree([0]).toRadians() ...
        ) ...
        );
    
CsCright = CrossSectSolidRect( ...
        'name', 'Cond2', ...
        'dim_w',DimMillimeter(2),....
        'dim_h',DimMillimeter(25),...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([16,2.5]), ...
            'theta', DimDegree([0]).toRadians() ...
        ) ...
        );
    
condL = Component( ...
        'name', 'LeftCoil', ...
        'crossSections', CsCleft, ...
        'material', MaterialGeneric('name', 'Copper: 5.77e7 Siemens/meter'), ...
        'makeSolid', MakeExtrude( ...
            'location', Location3D( ...
                'anchor_xyz', DimMillimeter([0,0,0]), ...
                'rotate_xyz', DimDegree([0,0,0]).toRadians() ...
                ), ...
            'dim_depth', DimMillimeter(10)) ...
        );
condL.make(toolMn,toolMn);
toolMn.viewAll();

condR = Component( ...
        'name', 'RightCoil', ...
        'crossSections', CsCright, ...
        'material', MaterialGeneric('name', 'Copper: 5.77e7 Siemens/meter'), ...
        'makeSolid', MakeExtrude( ...
            'location', Location3D( ...
                'anchor_xyz', DimMillimeter([0,0,0]), ...
                'rotate_xyz', DimDegree([0,0,0]).toRadians() ...
                ), ...
            'dim_depth', DimMillimeter(10)) ...
        );

condR.make(toolMn,toolMn);
toolMn.viewAll();

%% Laminations
%REPLACE THE MATERIAL WITH A CONDUCTIVE STEEL MATERIAL MODEL
new_material = 'M-19 24 Ga non-zero conductivity';
old_material = 'M-19 24 Ga';
old_material_category = 'Non-Oriented AISI Silicon Steel Materials';
conductivity = 1900000;

mn_copySystemMaterial(toolMn.mn,old_material_category,old_material,new_material)
mn_setElectricConductivity(toolMn.mn,new_material,conductivity)

for i = 1:n
    lamCS(i) = CrossSectSolidRect( ...
        'name', ['csLam' num2str(i)], ...
        'dim_w',DimMillimeter(lamT),...
        'dim_h',DimMillimeter(30),...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([4 + lamT*(i-1),0]), ...
            'theta', DimDegree([0]).toRadians() ...
        ) ...
        );
    
    compLam(i) = Component( ...
        'name', ['Lam' num2str(i)], ...
        'crossSections', lamCS(i), ...
        'material', MaterialGeneric('name', new_material), ... %  Hiperco 50A 0.006 
        'makeSolid', MakeExtrude( ...
            'location', Location3D( ...
                'anchor_xyz', DimMillimeter([0,0,0]), ...
                'rotate_xyz', DimDegree([0,0,0]).toRadians() ...
                ), ...
            'dim_depth', DimMillimeter(10)) ...
        );
    
    compLam(i).make(toolMn,toolMn);
    toolMn.viewAll();
end


%% Create and setup winding
coilName = mn_d_makeSimpleCoil(toolMn.mn, 1, [{'LeftCoil'}, {'RightCoil'}]);
mn_d_setparameter(toolMn.doc, coilName, 'NumberOfTurns', CoilTurns, ...
    get(toolMn.consts,'infoNumberParameter'));

%% Setup Mesh
mn_d_setparameter(toolMn.doc, compAir.name, 'MaximumElementSize', ...
    sprintf('%g %%mm', MES_AirBox), ...
    get(toolMn.consts,'infoNumberParameter'));
mn_d_setparameter(toolMn.doc, condL.name, 'MaximumElementSize', ...
    sprintf('%g %%mm', MES_Conductors), ...
    get(toolMn.consts,'infoNumberParameter'));
mn_d_setparameter(toolMn.doc, condR.name, 'MaximumElementSize', ...
    sprintf('%g %%mm', MES_Conductors), ...
    get(toolMn.consts,'infoNumberParameter'));

for i = 1:length(compLam)
    mn_d_setparameter(toolMn.doc, compLam(i).name, 'MaximumElementSize', ...
    sprintf('%g %%mm', MES_Laminations), ...
    get(toolMn.consts,'infoNumberParameter'));
end

end