clear

%% Create Cross Section

stator1 = CrossSectOuterRotorStator( ...
        'name', 'stator1', ...
        'dim_alpha_st', DimDegree(30), ...
        'dim_alpha_so', DimDegree((30 / 2) * 0.25), ...
        'dim_r_si', DimMillimeter(15), ...
        'dim_d_sy', DimMillimeter(7.5), ...
        'dim_d_st', DimMillimeter(7.5), ...
        'dim_d_sp', DimMillimeter(5), ...
        'dim_d_so', DimMillimeter(3), ...
        'dim_w_st', DimMillimeter(7.5), ...
        'dim_r_st', DimMillimeter(0), ...
        'dim_r_sf', DimMillimeter(0), ...
        'dim_r_sb', DimMillimeter(0), ...
        'dim_Q', 8, ...
        'location', Location2D( ...
            'anchor_xy', DimMillimeter([0,0]), ...
            'theta', DimDegree(0).toRadians() ...
        ) ...
);

%% Instantiate AnsysMech Tool
scratch_path = "C:\Users\nhemenway\Desktop\APDL_Learning\Ansys_Scratch";

toolMech = AnsysMech();
toolMech.open(scratch_path, 'test_job');
toolMech.reset();
toolMech.preprocesser();

%% Draw Cross Section and Save to IGES File

stator1.draw(toolMech);

%after drawing the cross section we can save it to an iges file that can
%then be opened and viewed with any CAD software
iges_path = 'C:\Users\nhemenway\Desktop\APDL_Learning\stator_test';
toolMech.save_IGES(iges_path);










